In [1]:
#Q1 Write a Python Program to Add Two Matrices?

import numpy

a1 = numpy.array([[1,2,3],[4,5,6],[7,8,9]])
a2 = numpy.array([[10,11,12],[13,14,15],[16,17,18]])

temp1 = a1.ravel()
temp2 = a2.ravel()
temp3 = []
for i in range(len(temp1)):
    temp3.append(temp1[i] + temp2[i])

temp3 = numpy.array(temp3).reshape(3,3)

print(f"Addition of matrix  \n {a1} \n and \n {a2} \n  is \n {temp3}")
    
    

Addition of matrix  
 [[1 2 3]
 [4 5 6]
 [7 8 9]] 
 and 
 [[10 11 12]
 [13 14 15]
 [16 17 18]] 
  is 
 [[11 13 15]
 [17 19 21]
 [23 25 27]]


In [2]:
#Question 2 Write a Python Program to Multiply Two Matrices?

a1 = numpy.array([[1,2],[4,5],[7,8]])
a2 = numpy.array([[10,11,12],[13,14,15]])
a3 = numpy.zeros((a1.shape[0],a2.shape[1]))

sum = 0
n = 0
for i in range(a1.shape[0]):
    for j in range(a2.shape[1]):
        for k in range(a2.shape[0]):
            sum = sum + (a1[i][k] * a2[k][j] )
        a3[i][j] = sum
        sum = 0


print(f"Multiplication of matrix is \n \n {a1} \n and \n {a2} \n  is \n {a3}")



        
        
        
        
        
    




Multiplication of matrix is 
 
 [[1 2]
 [4 5]
 [7 8]] 
 and 
 [[10 11 12]
 [13 14 15]] 
  is 
 [[ 36.  39.  42.]
 [105. 114. 123.]
 [174. 189. 204.]]


In [3]:
#Question3 - Write a Python Program to Transpose a Matrix?

a = numpy.array([[1.,2.,3.],[4.,5.,6.],[7.,8.,9.]])

b = numpy.zeros((a.shape[0],a.shape[1]))
print(f"Input matrix is \n \n {a}")

print("Transpose of matrix is \n ")

for i in range(a.shape[0]):
    b[:,i] = a[i,:]
    
print(b)





Input matrix is 
 
 [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]
Transpose of matrix is 
 
[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]


In [4]:
#Question4 - Write a Python Program to Sort Words in Alphabetic Order?

test = "helloworld"
result = ''.join(sorted(test))
print(f"Input World is : {test}")
print(f"Output word in Sorted Aphabetical Order is :{result}")


Input World is : helloworld
Output word in Sorted Aphabetical Order is :dehllloorw


In [5]:
#Question5 - Write a Python Program to Remove Punctuation From a String?

teststring = "I'm learning Python. It's easy & simple to understand"

punct = '''!@#$%^&*()-[]{};:'"\,<>./?_~'''
optstring = ""
for i in teststring:
    if i not in punct:
        optstring = optstring + i
        
print(f"Input String with punctuation is \n {teststring} \n ")
print(f"Output String without punctuation is \n {optstring} \n ")


Input String with punctuation is 
 I'm learning Python. It's easy & simple to understand 
 
Output String without punctuation is 
 Im learning Python Its easy  simple to understand 
 
